(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "helm-bibtex")
(depends-on "markdown-mode")
(depends-on "markdown-preview")

